language: python
python:
- 3.6
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 edc_timepoint
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=edc_timepoint manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: ZH4Jvw9ZO4umgZwyB3wCsyMXfH7IpLiqypEakOSf5hDacoTQOmPcqq+2Pmwya7813p1A8b7obhCawFHwtilx49AHMZmHDHQDaMSPzP/+hXP+I2qWqYnxgQA5DJYOkHqLn7KK+z9/osVc9oHW76DUFrEvtAXzPCiGOTeLy/J+0r6HYOesB1XfVaL0/TeqdIO4hdm/eZ6HiCPi01h6qC9VT6STkLrrxw2RRcQjDxWqjkQ5mU7nn/uGSKDWgcapOEnkyLfIlNAQk7i5Q/vwzg3+PcUoni7bNEnTSL4t9beRTyTCy57TRHuJ8ERWFAgUOAMqujBsqsZAQLQcgeo4hOoZsI4beTlVVZzqYtomH3yJqOGFI0q2ZddG/87hcEu/CEh6pNU7NiKP00YeC0WTYQe2e2VC/KaXe9kY1qxunu/YmSPgcRonT4Qa8KS9xPYRw3fq3e/Ay+FvFPei1r47KW7QXkmrTpxteUSNQLhNAaVokqLrB9wWd6JPbBeb3tlh5KxOpndS8jm2/1uG4FqP9sqo/1I9aTVhT7NBma0wYTie3gI43/1fU3nAeOuSieEjk8RKtsqbelMUxY9I3Y19aI3uuP0t6g0pFMeps5oGt41cPBU6d3JjRn21R7CGFgRB2T1qdywSrmW0DlEF3KxCWoMCq57TbzdlmtMBQ6uFXnDHK6c=
